/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportReportIdRouteImport } from './routes/report.$reportId'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiV1RunRouteImport } from './routes/api/v1.run'
import { Route as ApiV1ReportRouteImport } from './routes/api/v1.report'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiV1RunIdRouteImport } from './routes/api/v1.run.$id'
import { Route as ApiV1ListTypeRouteImport } from './routes/api/v1.list.$type'
import { Route as ApiV1RunRunIdClaimRouteImport } from './routes/api/v1.run.$runId.claim'
import { Route as ApiV1RunIdTriggerRouteImport } from './routes/api/v1.run.$id.trigger'
import { Route as ApiV1ReportIdDoneRouteImport } from './routes/api/v1.report.$id.done'

const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReportIdRoute = ReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunRoute = ApiV1RunRouteImport.update({
  id: '/api/v1/run',
  path: '/api/v1/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportRoute = ApiV1ReportRouteImport.update({
  id: '/api/v1/report',
  path: '/api/v1/report',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunIdRoute = ApiV1RunIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1RunRoute,
} as any)
const ApiV1ListTypeRoute = ApiV1ListTypeRouteImport.update({
  id: '/api/v1/list/$type',
  path: '/api/v1/list/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunRunIdClaimRoute = ApiV1RunRunIdClaimRouteImport.update({
  id: '/$runId/claim',
  path: '/$runId/claim',
  getParentRoute: () => ApiV1RunRoute,
} as any)
const ApiV1RunIdTriggerRoute = ApiV1RunIdTriggerRouteImport.update({
  id: '/trigger',
  path: '/trigger',
  getParentRoute: () => ApiV1RunIdRoute,
} as any)
const ApiV1ReportIdDoneRoute = ApiV1ReportIdDoneRouteImport.update({
  id: '/$id/done',
  path: '/$id/done',
  getParentRoute: () => ApiV1ReportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/explore': typeof ExploreRoute
  '/reports': typeof ReportsRoute
  '/runs': typeof RunsRoute
  '/demo/table': typeof DemoTableRoute
  '/report/$reportId': typeof ReportReportIdRoute
  '/api/v1/report': typeof ApiV1ReportRouteWithChildren
  '/api/v1/run': typeof ApiV1RunRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/v1/list/$type': typeof ApiV1ListTypeRoute
  '/api/v1/run/$id': typeof ApiV1RunIdRouteWithChildren
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/api/v1/report/$id/done': typeof ApiV1ReportIdDoneRoute
  '/api/v1/run/$id/trigger': typeof ApiV1RunIdTriggerRoute
  '/api/v1/run/$runId/claim': typeof ApiV1RunRunIdClaimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/explore': typeof ExploreRoute
  '/reports': typeof ReportsRoute
  '/runs': typeof RunsRoute
  '/demo/table': typeof DemoTableRoute
  '/report/$reportId': typeof ReportReportIdRoute
  '/api/v1/report': typeof ApiV1ReportRouteWithChildren
  '/api/v1/run': typeof ApiV1RunRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/v1/list/$type': typeof ApiV1ListTypeRoute
  '/api/v1/run/$id': typeof ApiV1RunIdRouteWithChildren
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/api/v1/report/$id/done': typeof ApiV1ReportIdDoneRoute
  '/api/v1/run/$id/trigger': typeof ApiV1RunIdTriggerRoute
  '/api/v1/run/$runId/claim': typeof ApiV1RunRunIdClaimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/explore': typeof ExploreRoute
  '/reports': typeof ReportsRoute
  '/runs': typeof RunsRoute
  '/demo/table': typeof DemoTableRoute
  '/report/$reportId': typeof ReportReportIdRoute
  '/api/v1/report': typeof ApiV1ReportRouteWithChildren
  '/api/v1/run': typeof ApiV1RunRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/v1/list/$type': typeof ApiV1ListTypeRoute
  '/api/v1/run/$id': typeof ApiV1RunIdRouteWithChildren
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/api/v1/report/$id/done': typeof ApiV1ReportIdDoneRoute
  '/api/v1/run/$id/trigger': typeof ApiV1RunIdTriggerRoute
  '/api/v1/run/$runId/claim': typeof ApiV1RunRunIdClaimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/explore'
    | '/reports'
    | '/runs'
    | '/demo/table'
    | '/report/$reportId'
    | '/api/v1/report'
    | '/api/v1/run'
    | '/demo/api/names'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/v1/list/$type'
    | '/api/v1/run/$id'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/api/v1/report/$id/done'
    | '/api/v1/run/$id/trigger'
    | '/api/v1/run/$runId/claim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/explore'
    | '/reports'
    | '/runs'
    | '/demo/table'
    | '/report/$reportId'
    | '/api/v1/report'
    | '/api/v1/run'
    | '/demo/api/names'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/v1/list/$type'
    | '/api/v1/run/$id'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/api/v1/report/$id/done'
    | '/api/v1/run/$id/trigger'
    | '/api/v1/run/$runId/claim'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/explore'
    | '/reports'
    | '/runs'
    | '/demo/table'
    | '/report/$reportId'
    | '/api/v1/report'
    | '/api/v1/run'
    | '/demo/api/names'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/v1/list/$type'
    | '/api/v1/run/$id'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/api/v1/report/$id/done'
    | '/api/v1/run/$id/trigger'
    | '/api/v1/run/$runId/claim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  ExploreRoute: typeof ExploreRoute
  ReportsRoute: typeof ReportsRoute
  RunsRoute: typeof RunsRoute
  DemoTableRoute: typeof DemoTableRoute
  ReportReportIdRoute: typeof ReportReportIdRoute
  ApiV1ReportRoute: typeof ApiV1ReportRouteWithChildren
  ApiV1RunRoute: typeof ApiV1RunRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiV1ListTypeRoute: typeof ApiV1ListTypeRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$reportId': {
      id: '/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof ReportReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/run': {
      id: '/api/v1/run'
      path: '/api/v1/run'
      fullPath: '/api/v1/run'
      preLoaderRoute: typeof ApiV1RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/report': {
      id: '/api/v1/report'
      path: '/api/v1/report'
      fullPath: '/api/v1/report'
      preLoaderRoute: typeof ApiV1ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/run/$id': {
      id: '/api/v1/run/$id'
      path: '/$id'
      fullPath: '/api/v1/run/$id'
      preLoaderRoute: typeof ApiV1RunIdRouteImport
      parentRoute: typeof ApiV1RunRoute
    }
    '/api/v1/list/$type': {
      id: '/api/v1/list/$type'
      path: '/api/v1/list/$type'
      fullPath: '/api/v1/list/$type'
      preLoaderRoute: typeof ApiV1ListTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/run/$runId/claim': {
      id: '/api/v1/run/$runId/claim'
      path: '/$runId/claim'
      fullPath: '/api/v1/run/$runId/claim'
      preLoaderRoute: typeof ApiV1RunRunIdClaimRouteImport
      parentRoute: typeof ApiV1RunRoute
    }
    '/api/v1/run/$id/trigger': {
      id: '/api/v1/run/$id/trigger'
      path: '/trigger'
      fullPath: '/api/v1/run/$id/trigger'
      preLoaderRoute: typeof ApiV1RunIdTriggerRouteImport
      parentRoute: typeof ApiV1RunIdRoute
    }
    '/api/v1/report/$id/done': {
      id: '/api/v1/report/$id/done'
      path: '/$id/done'
      fullPath: '/api/v1/report/$id/done'
      preLoaderRoute: typeof ApiV1ReportIdDoneRouteImport
      parentRoute: typeof ApiV1ReportRoute
    }
  }
}

interface ApiV1ReportRouteChildren {
  ApiV1ReportIdDoneRoute: typeof ApiV1ReportIdDoneRoute
}

const ApiV1ReportRouteChildren: ApiV1ReportRouteChildren = {
  ApiV1ReportIdDoneRoute: ApiV1ReportIdDoneRoute,
}

const ApiV1ReportRouteWithChildren = ApiV1ReportRoute._addFileChildren(
  ApiV1ReportRouteChildren,
)

interface ApiV1RunIdRouteChildren {
  ApiV1RunIdTriggerRoute: typeof ApiV1RunIdTriggerRoute
}

const ApiV1RunIdRouteChildren: ApiV1RunIdRouteChildren = {
  ApiV1RunIdTriggerRoute: ApiV1RunIdTriggerRoute,
}

const ApiV1RunIdRouteWithChildren = ApiV1RunIdRoute._addFileChildren(
  ApiV1RunIdRouteChildren,
)

interface ApiV1RunRouteChildren {
  ApiV1RunIdRoute: typeof ApiV1RunIdRouteWithChildren
  ApiV1RunRunIdClaimRoute: typeof ApiV1RunRunIdClaimRoute
}

const ApiV1RunRouteChildren: ApiV1RunRouteChildren = {
  ApiV1RunIdRoute: ApiV1RunIdRouteWithChildren,
  ApiV1RunRunIdClaimRoute: ApiV1RunRunIdClaimRoute,
}

const ApiV1RunRouteWithChildren = ApiV1RunRoute._addFileChildren(
  ApiV1RunRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  ExploreRoute: ExploreRoute,
  ReportsRoute: ReportsRoute,
  RunsRoute: RunsRoute,
  DemoTableRoute: DemoTableRoute,
  ReportReportIdRoute: ReportReportIdRoute,
  ApiV1ReportRoute: ApiV1ReportRouteWithChildren,
  ApiV1RunRoute: ApiV1RunRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiV1ListTypeRoute: ApiV1ListTypeRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
